version: "3"
services:
  planets-api:
    image: planets-api
    build: .
    environment:
      SERVER_HOST: "http://localhost:8080"
      MONGO_URI: "mongo:27017"
      SW_API: "http://swapi.dev/api/"
    ports:
      - "8080:8080"

  mongo:
    image: mongo:4
    ports:
      - 27017:27017
