basePath: /api/v1
definitions:
  models.PaginaResultado:
    properties:
      anterior:
        type: string
      dados:
        type: object
      pagina:
        type: integer
      proxima:
        type: string
      total_paginas:
        type: integer
    type: object
  models.Planeta:
    properties:
      _id:
        type: string
      aparicoes_em_filmes:
        type: integer
      atualizado_em:
        type: string
      clima:
        type: string
      criado_em:
        type: string
      nome:
        type: string
      terreno:
        type: string
    required:
    - clima
    - nome
    - terreno
    type: object
  models.PlanetaInput:
    properties:
      aparicoes_em_filmes:
        type: integer
      clima:
        type: string
      nome:
        type: string
      terreno:
        type: string
    required:
    - clima
    - nome
    - terreno
    type: object
  models.ResultadoInsert:
    properties:
      id:
        type: string
    type: object
info:
  contact:
    name: Thalyson
  description: API para manter planetas
  license: {}
  title: Planets API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Retorna links para os controllers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Raiz
      tags:
      - Raiz
  /planetas:
    get:
      consumes:
      - application/json
      description: Busca paginada de planetas
      parameters:
      - description: buscar por nome do planeta
        in: query
        name: busca
        type: string
      - description: pular X itens no resultado
        in: query
        name: skip
        type: integer
      - description: limite de itens por pagina
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaginaResultado'
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Busca planetas
      tags:
      - Planetas
    post:
      consumes:
      - application/json
      description: Insere um novo planeta
      parameters:
      - description: Dados de um planeta
        in: body
        name: planeta_input
        required: true
        schema:
          $ref: '#/definitions/models.PlanetaInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ResultadoInsert'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Inserir Planeta
      tags:
      - Planetas
  /planetas/{id}:
    delete:
      consumes:
      - application/json
      description: Remove um planeta usando seu ID
      parameters:
      - description: ID do planeta a ser deletado
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Item removido
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
      summary: Remover Planeta
      tags:
      - Planetas
    get:
      consumes:
      - application/json
      description: Busca um planeta por ID
      parameters:
      - description: id do planeta a ser buscado
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Planeta'
        "404":
          description: Not found
          schema:
            type: string
      summary: Busca planeta
      tags:
      - Planetas
swagger: "2.0"
